version: "2"

services:
  mysql:
    image: scorcher/pinba-server
    ports:
      - "3306:3306"
      - "30002:30002"
    container_name: amsterdam-php-pinba-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  php:
    build:
      dockerfile: Dockerfile.php
      context: .
    container_name: amsterdam-php-pinba-php
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - .:/code

#  statsd:
#    build:
#      dockerfile: Dockerfile.statsd
#      context: .
#    container_name: amsterdam-php-pinba-statsd
#    ports:
#      - "8125:8125"
#    volumes:
#      - ./statsite.conf:/statsite.conf
#
#  influxdb:
#    image: influxdb
#    ports:
#      - "8083:8083"
#      - "8086:8086"
#      - "2003:2003"
#    expose:
#      - "8086"
#      - "8083"
#      - "2003"
#    container_name: amsterdam-php-pinba-influxdb
#    environment:
#      INFLUXDB_GRAPHITE_ENABLED: "true"
#    volumes:
#      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
